name: Daily Challenge

on:
  schedule:
    # Every day at 9:00 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # allows manual trigger

jobs:
  generate-challenge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js (for JS challenges)
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Generate challenge
      run: |
        DAY_FILE=".day"
        REPO_DIR="${{ github.workspace }}"

        # Initialize day counter
        if [ ! -f "$REPO_DIR/$DAY_FILE" ]; then
          echo 1 > "$REPO_DIR/$DAY_FILE"
        fi

        DAY=$(cat "$REPO_DIR/$DAY_FILE")
        DAY_DIR="$REPO_DIR/day$(printf "%02d" $DAY)"
        mkdir -p "$DAY_DIR"

        # Simple JS FizzBuzz example (replace with API call if needed)
        echo "## Day $DAY Challenge: FizzBuzz" > "$DAY_DIR/challenge.md"
        echo 'Write a function that prints numbers 1 to n, replacing multiples of 3 with "fizz", 5 with "buzz", and both with "fizzbuzz".' >> "$DAY_DIR/challenge.md"
        echo '```javascript' >> "$DAY_DIR/challenge.md"
        echo 'function fizzBuzz(n) { const res = []; for(let i=1;i<=n;i++){ if(i%15===0) res.push("fizzbuzz"); else if(i%3===0) res.push("fizz"); else if(i%5===0) res.push("buzz"); else res.push(i); } return res; }' >> "$DAY_DIR/challenge.md"
        echo '```' >> "$DAY_DIR/challenge.md"

        # Increment day
        echo $((DAY+1)) > "$REPO_DIR/$DAY_FILE"

    - name: Commit and push
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "Day $DAY: Automatic Coding Challenge" || echo "No changes to commit"
        git push
